library(shiny)
library(plotly)
library(ggplot2)
library(dplyr)
library(tidyr)

# =========================================================
# UI
# =========================================================

plotsUI <- function(id){
  
  ns <- NS(id)
  
  div(
    class = "content",
    
    h2("📊 | RNA PLOTS"),
    
    br(),
    
    tabsetPanel(
      
      # ===================================================
      # EXPRESSION
      # ===================================================
      
      tabPanel(
        "Expression",
        
        br(),
        
        div(
          class = "filter-box",
          
          tags$h3(
            style="color:#8b1e5b;font-weight:700;margin-top:0;",
            "Expression overview"
          ),
          
          p(
            style="font-size:15px; line-height:1.7;",
            "Visualization of RNA expression values comparing the affected sample against control cohort expression."
          ),
          
          tags$ul(
            style="line-height:1.8;",
            
            tags$li(tags$b("Blue range: "), "minimum to maximum TPM observed in controls"),
            tags$li(tags$b("Blue diamond: "), "median TPM in controls"),
            tags$li(tags$b("Magenta point: "), "expression in the affected sample"),
            tags$li(tags$b("Data source: "), "RNA TPM + DROP aberrant expression")
          )
        ),
        
        br(),
        
        div(
          class = "table-box",
          plotlyOutput(ns("expression_plot"), height = "700px")
        )
      ),
      
      # ===================================================
      # VOLCANO
      # ===================================================
      
      tabPanel(
        "Volcano",
        
        br(),
        
        div(
          class = "filter-box",
          
          tags$h3(
            style="color:#8b1e5b;font-weight:700;margin-top:0;",
            "Volcano plot"
          ),
          
          p(
            style="font-size:15px; line-height:1.7;",
            "Global overview of aberrant expression results generated by DROP."
          ),
          
          tags$ul(
            style="line-height:1.8;",
            
            tags$li(tags$b("X-axis: "), "log2 fold change"),
            tags$li(tags$b("Y-axis: "), "-log10 adjusted p-value"),
            tags$li(tags$b("Blue points: "), "non-significant genes"),
            tags$li(tags$b("Magenta points: "), "significant genes")
          )
        ),
        
        br(),
        
        div(
          class = "table-box",
          plotlyOutput(ns("volcano_plot"), height = "700px")
        )
      ),
      
      # ===================================================
      # Z-SCORE
      # ===================================================
      
      tabPanel(
        "Z-score",
        
        br(),
        
        div(
          class = "filter-box",
          
          tags$h3(
            style="color:#8b1e5b;font-weight:700;margin-top:0;",
            "Aberrant expression z-scores"
          ),
          
          p(
            style="font-size:15px; line-height:1.7;",
            "Most extreme expression outliers identified by DROP."
          ),
          
          tags$ul(
            style="line-height:1.8;",
            
            tags$li(tags$b("Positive z-score: "), "gene overexpression"),
            tags$li(tags$b("Negative z-score: "), "gene underexpression"),
            tags$li(tags$b("Dashed lines: "), "common outlier thresholds"),
            tags$li(tags$b("Data source: "), "DROP aberrant expression")
          )
        ),
        
        br(),
        
        div(
          class = "table-box",
          plotlyOutput(ns("zscore_plot"), height = "700px")
        )
      ),
      
      # ===================================================
      # SPLICING
      # ===================================================
      
      tabPanel(
        "Splicing",
        
        br(),
        
        div(
          class = "filter-box",
          
          tags$h3(
            style="color:#8b1e5b;font-weight:700;margin-top:0;",
            "Aberrant splicing events"
          ),
          
          p(
            style="font-size:15px; line-height:1.7;",
            "Visualization of the most significant splicing alterations detected by DROP."
          ),
          
          tags$ul(
            style="line-height:1.8;",
            
            tags$li(tags$b("Each point: "), "one splice junction"),
            tags$li(tags$b("Y-axis: "), "delta PSI"),
            tags$li(tags$b("Large absolute values: "), "stronger splicing alteration"),
            tags$li(tags$b("Data source: "), "DROP aberrant splicing")
          )
        ),
        
        br(),
        
        div(
          class = "table-box",
          plotlyOutput(ns("psi_plot"), height = "700px")
        )
      ),
      
      # ===================================================
      # MAE
      # ===================================================
      
      tabPanel(
        "MAE",
        
        br(),
        
        div(
          class = "filter-box",
          
          tags$h3(
            style="color:#8b1e5b;font-weight:700;margin-top:0;",
            "Monoallelic expression"
          ),
          
          p(
            style="font-size:15px; line-height:1.7;",
            "Allelic imbalance visualization for variants detected in RNA-seq."
          ),
          
          tags$ul(
            style="line-height:1.8;",
            
            tags$li(tags$b("Blue bars: "), "reference allele counts"),
            tags$li(tags$b("Magenta bars: "), "alternative allele counts"),
            tags$li(tags$b("Strong imbalance: "), "possible monoallelic expression"),
            tags$li(tags$b("Data source: "), "DROP MAE")
          )
        ),
        
        br(),
        
        div(
          class = "table-box",
          plotlyOutput(ns("mae_plot"), height = "700px")
        )
      )
    )
  )
}

# =========================================================
# SERVER
# =========================================================

plotsServer <- function(id, pool){
  
  moduleServer(id, function(input, output, session){
    
    # =====================================================
    # EXPRESSION DATA
    # =====================================================
    
    expression_data <- reactive({
      
      rna <- get_rna(pool)
      
      if(nrow(rna) == 0){
        return(data.frame())
      }
      
      drop <- get_drop_expr(pool)
      
      expr <- rna %>%
        transmute(
          gene_name,
          case_expression = as.numeric(tpm),
          control_min = as.numeric(min_TPM),
          control_median = as.numeric(median_TPM),
          control_max = as.numeric(max_TPM)
        )
      
      if(nrow(drop) > 0){
        
        drop_clean <- drop %>%
          transmute(
            gene_name = toupper(trimws(hgncSymbol)),
            zscore = as.numeric(zScore),
            padj = as.numeric(padjust),
            log2fc = as.numeric(l2fc)
          )
        
        expr <- expr %>%
          mutate(
            gene_name = toupper(trimws(gene_name))
          ) %>%
          left_join(drop_clean, by = "gene_name")
      }
      
      expr
    })
    
    # =====================================================
    # SPLICING DATA
    # =====================================================
    
    splicing_data <- reactive({
      
      df <- get_drop_splicing(pool)
      
      if(nrow(df) == 0){
        return(data.frame())
      }
      
      df %>%
        transmute(
          gene_name = hgncSymbol,
          
          junction_id = paste(
            seqnames,
            start,
            end,
            sep = "_"
          ),
          
          psi = as.numeric(psiValue),
          delta_psi = as.numeric(deltaPsi),
          padj = as.numeric(padjust)
        )
    })
    
    # =====================================================
    # MAE DATA
    # =====================================================
    
    mae_data <- reactive({
      
      df <- get_drop_mae(pool)
      
      if(nrow(df) == 0){
        return(data.frame())
      }
      
      df %>%
        transmute(
          
          gene_name,
          
          variant_id = variantID,
          
          ref_count = suppressWarnings(as.numeric(refCount)),
          
          alt_count = suppressWarnings(as.numeric(altCount))
        ) %>%
        
        filter(
          !is.na(ref_count),
          !is.na(alt_count)
        )
    })
    
    # =====================================================
    # EXPRESSION PLOT
    # =====================================================
    
    output$expression_plot <- renderPlotly({
      
      df <- expression_data()
      
      validate(
        need(nrow(df) > 0,
             "No RNA expression data loaded")
      )
      
      df_plot <- df %>%
        filter(!is.na(zscore)) %>%
        slice_max(order_by = abs(zscore), n = 20)
      
      p <- ggplot(df_plot) +
        
        geom_segment(
          aes(
            x = gene_name,
            xend = gene_name,
            y = control_min,
            yend = control_max
          ),
          linewidth = 2,
          alpha = 0.6,
          color = "#2c7fb8"
        ) +
        
        geom_point(
          aes(
            x = gene_name,
            y = control_median,
            text = paste0(
              "Gene: ", gene_name,
              "<br>Median TPM: ",
              round(control_median, 2)
            )
          ),
          size = 4,
          shape = 18,
          color = "#2c7fb8"
        ) +
        
        geom_point(
          aes(
            x = gene_name,
            y = case_expression,
            text = paste0(
              "Gene: ", gene_name,
              "<br>Case TPM: ",
              round(case_expression, 2),
              "<br>Z-score: ",
              round(zscore, 2),
              "<br>padj: ",
              signif(padj, 3)
            )
          ),
          size = 5,
          color = "#8b1e5b"
        ) +
        
        coord_flip() +
        
        theme_bw(base_size = 13) +
        
        theme(
          panel.grid.minor = element_blank(),
          
          plot.title = element_text(
            color = "#8b1e5b",
            face = "bold"
          )
        ) +
        
        labs(
          title = "Top aberrantly expressed genes",
          x = "",
          y = "TPM"
        )
      
      ggplotly(p, tooltip = "text")
    })
    
    # =====================================================
    # VOLCANO
    # =====================================================
    
    output$volcano_plot <- renderPlotly({
      
      df <- expression_data() %>%
        filter(
          !is.na(log2fc),
          !is.na(padj),
          padj > 0
        ) %>%
        mutate(
          minus_log10_padj = -log10(padj),
          
          significant = ifelse(
            padj < 0.05,
            "Significant",
            "Non-significant"
          )
        )
      
      validate(
        need(nrow(df) > 0,
             "No DROP expression data loaded")
      )
      
      p <- ggplot(
        df,
        aes(
          x = log2fc,
          y = minus_log10_padj,
          
          color = significant,
          
          text = paste0(
            "Gene: ", gene_name,
            "<br>log2FC: ",
            round(log2fc, 2),
            "<br>padj: ",
            signif(padj, 3),
            "<br>Z-score: ",
            round(zscore, 2)
          )
        )
      ) +
        
        geom_point(alpha = 0.8, size = 2) +
        
        scale_color_manual(
          values = c(
            "Significant" = "#8b1e5b",
            "Non-significant" = "#2c7fb8"
          )
        ) +
        
        theme_bw(base_size = 14) +
        
        theme(
          panel.grid.minor = element_blank(),
          
          plot.title = element_text(
            color = "#8b1e5b",
            face = "bold"
          )
        ) +
        
        labs(
          title = "Volcano plot",
          x = "log2 Fold Change",
          y = "-log10 adjusted p-value"
        )
      
      ggplotly(p, tooltip = "text")
    })
    
    # =====================================================
    # ZSCORE
    # =====================================================
    
    output$zscore_plot <- renderPlotly({
      
      df <- expression_data() %>%
        filter(!is.na(zscore))
      
      validate(
        need(nrow(df) > 0,
             "No z-score data loaded")
      )
      
      df_plot <- df %>%
        arrange(zscore) %>%
        slice(c(1:20, (n()-19):n()))
      
      p <- ggplot(
        df_plot,
        aes(
          x = reorder(gene_name, zscore),
          y = zscore,
          
          text = paste0(
            "Gene: ", gene_name,
            "<br>Z-score: ",
            round(zscore, 2),
            "<br>padj: ",
            signif(padj, 3)
          )
        )
      ) +
        
        geom_hline(
          yintercept = c(-3, 3),
          linetype = "dashed",
          color = "#8b1e5b"
        ) +
        
        geom_point(
          color = "#2c7fb8",
          size = 3
        ) +
        
        coord_flip() +
        
        theme_bw(base_size = 13) +
        
        theme(
          panel.grid.minor = element_blank(),
          
          plot.title = element_text(
            color = "#8b1e5b",
            face = "bold"
          )
        ) +
        
        labs(
          title = "Aberrant expression z-scores",
          x = "Gene",
          y = "Z-score"
        )
      
      ggplotly(p, tooltip = "text")
    })
    
    # =====================================================
    # PSI
    # =====================================================
    
    output$psi_plot <- renderPlotly({
      
      df <- splicing_data()
      
      validate(
        need(nrow(df) > 0,
             "No splicing data loaded")
      )
      
      df_plot <- df %>%
        arrange(padj) %>%
        slice(1:30)
      
      p <- ggplot(
        df_plot,
        aes(
          x = reorder(junction_id, delta_psi),
          y = delta_psi,
          
          text = paste0(
            "Gene: ", gene_name,
            "<br>Junction: ", junction_id,
            "<br>PSI: ", round(psi, 3),
            "<br>Delta PSI: ", round(delta_psi, 3),
            "<br>padj: ", signif(padj, 3)
          )
        )
      ) +
        
        geom_point(
          color = "#8b1e5b",
          size = 4
        ) +
        
        coord_flip() +
        
        theme_bw(base_size = 13) +
        
        theme(
          panel.grid.minor = element_blank(),
          
          plot.title = element_text(
            color = "#8b1e5b",
            face = "bold"
          )
        ) +
        
        labs(
          title = "Top aberrant splicing junctions",
          x = "Junction",
          y = "Delta PSI"
        )
      
      ggplotly(p, tooltip = "text")
    })
    
    # =====================================================
    # MAE
    # =====================================================
    
    output$mae_plot <- renderPlotly({
      
      df <- mae_data()
      
      validate(
        need(nrow(df) > 0,
             "No MAE data loaded")
      )
      
      df_long <- df %>%
        mutate(
          imbalance = abs(ref_count - alt_count)
        ) %>%
        slice_max(
          imbalance,
          n = 20
        ) %>%
        pivot_longer(
          cols = c(ref_count, alt_count),
          names_to = "allele",
          values_to = "count"
        )
      
      p <- ggplot(
        df_long,
        aes(
          x = variant_id,
          y = count,
          fill = allele,
          
          text = paste0(
            "Gene: ", gene_name,
            "<br>Variant: ", variant_id,
            "<br>", allele, ": ", count
          )
        )
      ) +
        
        geom_bar(
          stat = "identity",
          position = "stack"
        ) +
        
        scale_fill_manual(
          values = c(
            "ref_count" = "#2c7fb8",
            "alt_count" = "#8b1e5b"
          )
        ) +
        
        coord_flip() +
        
        theme_bw(base_size = 13) +
        
        theme(
          panel.grid.minor = element_blank(),
          
          plot.title = element_text(
            color = "#8b1e5b",
            face = "bold"
          )
        ) +
        
        labs(
          title = "Top monoallelic expression variants",
          x = "Variant",
          y = "Allelic counts"
        )
      
      ggplotly(p, tooltip = "text")
    })
  })
}